### ISSUE TITLE
Add USB Support for Atmosphere 0.16.0 and Firmware 11.0.0

### ISSUE THREAD

**Issue by EmreTech** [Huntereb/Awoo-Installer#115]
Hey there! Please update Awoo Installer for the new features of Atmosphere 0.16.0 and Firmware 11.0.0. Without updating, it won't work at all.

**Comment by 20Phoenix** [comment]
@Huntereb 
After use the system always crashes sooner or later, a rebuilt with new libnx is needed anyway.

**Comment by Polytoo** [comment]
Hey, guys!
I have compiled a pre-release version [1.3.5b](https://github.com/Polytoo/Awoo-Installer/releases/download/1.3.5b/Awoo-Installer-1.3.5b.zip).

I didn't make a PR here just because it was based on pre-release libnx code.

I am going to make a PR after libnx release a new version for fw11.0.0.

**Comment by EmreTech** [comment]
Okay, that's great! Hopefully, Huntereb can update Awoo Installer soon.

**Comment by HookedBehemoth** [comment]
New release is out.
