### ISSUE TITLE
Partially installed contents Error

### ISSUE THREAD

**Issue by wronglebowsk** [Huntereb/Awoo-Installer#51]
I'm getting the "Partially installed contents can be removed from the System Settings applet." error on some titles. I can't find any entries in the system settings applet or in goldleaf. Any other ideas?

**Comment by deadair3210** [comment]
partially installed titles would show up as a empty square with a never ending loading spinner in it and a blank title in the data management with however big the title got before it failed

**Comment by wronglebowsk** [comment]
> partially installed titles would show up as a empty square with a never ending loading spinner in it and a blank title in the data management with however big the title got before it failed

I have seen these before but I don’t have any right now. I’ve made sure I’m checking all apps and I’ve reviewed every menu I can think of. I’m using EMUMMC Atmosphere 9.1. Is there anything else I can try?

**Comment by Huntereb** [comment]
Awoo Installer gives you this information when a file fails to install properly. You may or may not have partially installed contents if the file instantly fails to install. Just make sure your backup was properly dumped.

**Comment by WeetbixNMilk** [comment]
I'm having the same issue where an install fails, says there is partially installed content and no data is present in "data management" -> "software" to remove. I'm using the latest Atmosphere Kosmos, is there a way to manually delete content or overwrite existing data?
Screenshots attached.
![awoo](https://user-images.githubusercontent.com/66398995/83708956-db079580-a660-11ea-9f5f-8562ef2c07e1.jpg)
![software](https://user-images.githubusercontent.com/66398995/83708957-dc38c280-a660-11ea-930e-114b972e4464.jpg)

**Comment by Masamune3210** [comment]
> > Do not use exfat unless you really like your card corrupting for exceedingly dumb reasons/no reason at all. Use fat32
> 
> I use exFat on 256gb microsd Every time I corrupted my memory card, it was by removing the card without ejecting correctly.
> 
> Now that doesn't happen anymore

The switch itself will corrupt exfat filesystems a lot due to the switch's exfat fs driver being complete garbage and violating the spec in a lot of places. Believe me, exfat on a switch WILL end up biting you eventually. Besides, there is nothing that you can do on exfat that you can't do on fat32 so it's just not worth the anguish usually

**Comment by uchyyy** [comment]
Hi all!

I am pretty new in the forum so sorry if I'm not strictly following any rules...

I'm encountering the same problem when installing several games. I tried to format the SD card, delete all saved data (both SD and switch memory) but still doesnt' work...it shows the message that some games are partially installed and that i should delete them in the first place. 

I am on the last atmosphere version and with all sigthpatches updated. Tried both Awoo and Tinwoo. Installed the whole system several times...can't find any solution so far :(

**Comment by gutss-666** [comment]
I suffered from the same issue and created the account just to share with you what did resolve the problem for me :)
I corrupted by game files by removing the SD card and trying to reinstall it from the official shop.

Go to your SD card, you can do it 'remotely' too via Hakate, aka:

1. Reboot your switch to Hekate
2. Click on "Tools" -> "USB Tools" and mount your card by clicking "SD Card"
3. Once on your SD, go to "Nintendo" folder and then -> Contents\registered
4. Filter folders by date, you can also check the size of the folder to determine if they contain any data

I deleted all the folders with the date of when I was trying to do the install.
I verified that the Saves remained intact after deleting (from the "registered" folder, as it was not present in the sys app) and reinstalling the game via Awoo.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/99767400/154155616-5eab0e4f-47aa-4f75-a858-90e8a0921bda.png">

**Comment by Hykciv** [comment]
> I'm getting the "Partially installed contents can be removed from the System Settings applet." error on some titles. I can't find any entries in the system settings applet or in goldleaf. Any other ideas?

Hi there,

Probably you moved on but, just in case someone else comes across your post:

I was getting the same thing. In my case, I realized I was doing something different than I should so, these are the steps that worked for me. Since to install anything you MUST NOT be on "Applet mode" (the Atmosphere menu to which you get by by clicking the "Album" icon that says on the top "Applet Mode" with a red circle) you need to do:

1. Enter RCM mode (For example, use the tinfoil method)

2. Inject Hekate (to boot) (For ex., use TegraRCMGUI with a USB A to C cable).

3. Once Hekate launches, choose PAYLOADS and

4. Click Fusee.bin. This launches the SAME homebrew menu that one gets by choosing to boot the CFW Atmosphere from the Hekate menu BUT, in this way, one is running Atmosphere in FULL memory access mode (NOT in applet mode).

5. To enter the Atmosphere menu, hold "R" and click any app. and now one can see that the menu DOES NOT have the red circle that warns about being in Applet Mode, meaning, any app. one runs, has full access to the memory, meaning, can read but also WRITE.

6. Now one can run Awoo Installer and install our backups with ... ZERO ERRORS.

7. ENJOY

Note: If reading this helped you, please thumbs up or comment, so others know it works. :)

**Comment by Aklaszok** [comment]
I created account just to thank You!

**Comment by 188subd** [comment]
I found another way to fix this problem, it's quick and works for me.
Just need to modify hekate_ipl.ini 
you guys may following the link below :
https://www.reddit.com/r/SwitchPirates/comments/q2kxvd/fix_sigpatches_problem_when_booting_with_hekate/

**Comment by DOMA6994** [comment]
I truly wish you the best life hykciv
